name 'test-mongodb'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures test-mongodb'
long_description 'Installs/Configures test-mongodb'
version '0.1.0'
