name 'test-mongodb'
maintainer 'Sparkly Devops'
maintainer_email 'sparklydevops@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures test-mongodb'
long_description 'Installs/Configures test-mongodb'
version '0.3.1'

source_url = 'https://github.com/sparklydevops/test-mongodb'
issues_url = 'https://github.com/sparklydevops/test-mongodb/issues'
